### ISSUE TITLE
Bug affichage

### ISSUE THREAD

**Issue by ghost** [prismsoundzero/delicious-library-template#1]
![capture d ecran 2016-10-29 a 11 26 43](https://cloud.githubusercontent.com/assets/21335390/19829890/b6df81b6-9dec-11e6-9bd6-8bf1d0bb9b4f.png)

Bonjour,
J'ai voulu publier mon site avec votre template, mais l'affichage n'est pas correct. Avez-vous une idée de comment résoudre ?

Merci,
tonio67

**Comment by prismsoundzero** [comment]
Bonjour, effectivement on dirait que ni le javascript ni le css n'est chargé. Est-ce qu'une erreur s'affiche dans la console web ?

**Comment by ghost** [comment]
<img width="1597" alt="capture d ecran 2016-10-31 a 11 04 40" src="https://cloud.githubusercontent.com/assets/21335390/19850666/ef6fcd6a-9f59-11e6-924e-2c129c754a18.png">
Voila les erreurs affichées dans la console

**Comment by prismsoundzero** [comment]
Il semblerait que vous ayez copié le dossier "prismsoundzero.libraryhtmltemplate" de la racine et non celui qui se trouve dans le dossier "dist".
Je vais mettre à jour le texte d'installation qui n'est pas assez clair.

**Comment by prismsoundzero** [comment]
Voilà, c'est fait. J'ai ajouté également de l'aide pour configurer LastFM et Spotify.

**Comment by ghost** [comment]
Effectivement, problème réglé avec le bon dossier.
Merci à toi !
